spring.application.name=routeforge
spring.profiles.active=dev

# Server
server.port=8081

# H2 Console (Dev)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.probes.enabled=true

# OpenAPI/Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=VGhpcyBpcyBhIHZlcnkgc2VjdXJlIGtleSBmb3IgSlRXIGdlbmVyYXRpb24uIE5vIG9uZSBzaG91bGQgYmUgYWJsZSB0byBndWVzcyB0aGlzIGtleSE=
jwt.expiration=86400000
