spring.application.name=routeforge

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081
spring.jpa.hibernate.ddl-auto=create-drop


jwt.secret=VGhpcyBpcyBhIHZlcnkgc2VjdXJlIGtleSBmb3IgSlRXIGdlbmVyYXRpb24uIE5vIG9uZSBzaG91bGQgYmUgYWJsZSB0byBndWVzcyB0aGlzIGtleSE=
jwt.expiration=86400000